-- Oovy & Ray's Money — Database Schema
-- Generated by DeepSeek migration (2026-05-20)
-- Matches specs/oovy-ray-data-model-spec.md §8.1

-- 1. Enums
CREATE TYPE account_type AS ENUM ('CURRENT','SAVINGS','CREDIT','DEBT','TRACKING','EXTERNAL');
CREATE TYPE currency AS ENUM ('GBP','NZD');
CREATE TYPE transaction_type AS ENUM ('TRANSFER','RECURRING_INSTANCE','ONE_OFF','ADJUSTMENT','OPENING');
CREATE TYPE frequency AS ENUM ('WEEKLY','FORTNIGHTLY','MONTHLY','QUARTERLY','BIANNUAL');

-- 2. Accounts
CREATE TABLE accounts (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                    TEXT NOT NULL,
  type                    account_type NOT NULL,
  currency                currency NOT NULL,
  include_in_cash_balance BOOLEAN NOT NULL DEFAULT true,
  include_in_review       BOOLEAN NOT NULL DEFAULT true,
  opening_balance         DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  opening_date            DATE NOT NULL DEFAULT '2024-08-01',
  display_order           INTEGER NOT NULL DEFAULT 0,
  color_from              TEXT NOT NULL DEFAULT '#1a1a2e',
  color_to                TEXT NOT NULL DEFAULT '#0f3460',
  is_archived             BOOLEAN NOT NULL DEFAULT false,
  is_system               BOOLEAN NOT NULL DEFAULT false,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. Recurring Schedules
CREATE TABLE recurring_schedules (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name              TEXT,
  from_account_id   UUID NOT NULL REFERENCES accounts(id),
  to_account_id     UUID NOT NULL REFERENCES accounts(id),
  currency_from     currency NOT NULL,
  currency_to       currency NOT NULL,
  frequency         frequency NOT NULL,
  day_of_week       SMALLINT CHECK (day_of_week BETWEEN 0 AND 6),
  day_of_month      SMALLINT CHECK (day_of_month BETWEEN 1 AND 31),
  weekday_only      BOOLEAN NOT NULL DEFAULT false,
  start_date        DATE NOT NULL,
  end_date          DATE,
  effective_changes JSONB NOT NULL DEFAULT '[]',
  is_active         BOOLEAN NOT NULL DEFAULT true,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. Recurring Skips
CREATE TABLE recurring_skips (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recurring_id  UUID NOT NULL REFERENCES recurring_schedules(id) ON DELETE CASCADE,
  skip_date     DATE NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(recurring_id, skip_date)
);

-- 5. Recurring Overrides
CREATE TABLE recurring_overrides (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recurring_id    UUID NOT NULL REFERENCES recurring_schedules(id) ON DELETE CASCADE,
  original_date   DATE NOT NULL,
  override_date   DATE NOT NULL,
  amount_from     DECIMAL(12,2) NOT NULL,
  amount_to       DECIMAL(12,2) NOT NULL,
  name            TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(recurring_id, original_date)
);

-- 6. Transactions
CREATE TABLE transactions (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name              TEXT,
  type              transaction_type NOT NULL,
  from_account_id   UUID NOT NULL REFERENCES accounts(id),
  to_account_id     UUID NOT NULL REFERENCES accounts(id),
  amount_from       DECIMAL(12,2) NOT NULL,
  amount_to         DECIMAL(12,2) NOT NULL,
  currency_from     currency NOT NULL,
  currency_to       currency NOT NULL,
  transaction_date  DATE NOT NULL,
  recurring_id      UUID REFERENCES recurring_schedules(id) ON DELETE SET NULL,
  is_adjustment     BOOLEAN NOT NULL DEFAULT false,
  note              TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT different_accounts CHECK (from_account_id != to_account_id),
  CONSTRAINT positive_amounts CHECK (amount_from > 0 AND amount_to > 0)
);

CREATE INDEX idx_tx_from_date ON transactions(from_account_id, transaction_date);
CREATE INDEX idx_tx_to_date ON transactions(to_account_id, transaction_date);
CREATE INDEX idx_tx_date ON transactions(transaction_date);
CREATE INDEX idx_tx_recurring ON transactions(recurring_id) WHERE recurring_id IS NOT NULL;

-- 7. Reviews
CREATE TABLE reviews (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  review_date  DATE NOT NULL UNIQUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 8. Review Entries
CREATE TABLE review_entries (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  review_id       UUID NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
  account_id      UUID NOT NULL REFERENCES accounts(id),
  actual_balance  DECIMAL(12,2),
  budget_balance  DECIMAL(12,2) NOT NULL,
  variance        DECIMAL(12,2),
  was_skipped     BOOLEAN NOT NULL DEFAULT false,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(review_id, account_id)
);

-- 9. Settings
CREATE TABLE settings (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  summary_target_date       DATE,
  budget_comparison_date    DATE,
  exchange_rate_gbp_nzd     DECIMAL(10,6) NOT NULL DEFAULT 2.220000,
  exchange_rate_auto_fetch  BOOLEAN NOT NULL DEFAULT false,
  exchange_rate_updated_at  TIMESTAMPTZ,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Row Level Security
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE recurring_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE recurring_skips ENABLE ROW LEVEL SECURITY;
ALTER TABLE recurring_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE review_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_all_authenticated" ON accounts FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "allow_all_authenticated" ON transactions FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "allow_all_authenticated" ON recurring_schedules FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "allow_all_authenticated" ON recurring_skips FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "allow_all_authenticated" ON recurring_overrides FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "allow_all_authenticated" ON reviews FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "allow_all_authenticated" ON review_entries FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "allow_all_authenticated" ON settings FOR ALL USING (auth.role() = 'authenticated');

-- Budget Calculation Function
CREATE OR REPLACE FUNCTION calculate_budget(p_account_id UUID, p_date DATE)
RETURNS DECIMAL AS $$
DECLARE
  v_opening_balance DECIMAL;
  v_cr_sum DECIMAL;
  v_dr_sum DECIMAL;
BEGIN
  SELECT opening_balance INTO v_opening_balance FROM accounts WHERE id = p_account_id;
  SELECT COALESCE(SUM(amount_to), 0) INTO v_cr_sum
  FROM transactions WHERE to_account_id = p_account_id AND transaction_date <= p_date;
  SELECT COALESCE(SUM(amount_from), 0) INTO v_dr_sum
  FROM transactions WHERE from_account_id = p_account_id AND transaction_date <= p_date;
  RETURN v_opening_balance + v_cr_sum - v_dr_sum;
END;
$$ LANGUAGE plpgsql;

-- Realtime (run after enabling on dashboard)
-- ALTER PUBLICATION supabase_realtime ADD TABLE transactions;
-- ALTER PUBLICATION supabase_realtime ADD TABLE reviews;
-- ALTER PUBLICATION supabase_realtime ADD TABLE settings;
